### ISSUE TITLE
package github.com/maoueh/zap-pretty is not a main package

### ISSUE THREAD

**Issue by JuArce** [maoueh/zap-pretty#14]
When I try to install zap-pretty
`go install github.com/maoueh/zap-pretty@v0.3.1`
or `go install github.com/maoueh/zap-pretty@latest`

I get the following error 
`package github.com/maoueh/zap-pretty is not a main package`

If I try installing the version v0.3.0
`go install github.com/maoueh/zap-pretty@v0.3.0`
It works fine

Is this error expected?

**Comment by maoueh** [comment]
Yeah I switched the CLI to be under `cmd/zap-pretty` now, so to install from source from now on:

```
go install github.com/maoueh/zap-pretty/cmd/zap-pretty@latest
```

Sorry for the trouble, didn't think this change would cause problem.

**Comment by JuArce** [comment]
Thank you for the clarification. I pinned the version on our scripts
